//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarGames.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarGames.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ship {
            get {
                object obj = ResourceManager.GetObject("ship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triton
        ///Naiad
        ///Thalassa
        ///Despina
        ///Galetea
        ///Larissa
        ///Proteus
        ///Halimede
        ///Psamathe
        ///Sao
        ///Laomedeia
        ///Neso
        ///Ariel
        ///Umbriel
        ///Titania
        ///Oberon
        ///Miranda
        ///Cordelia
        ///Ophelia
        ///Bianca
        ///Cressida
        ///Desdemona
        ///Juliet
        ///Portia
        ///Rosalind
        ///Belinda
        ///Puck
        ///Caliban
        ///Sycorax
        ///Prospero
        ///Setebos
        ///Stephano
        ///Trinculo
        ///Francisco
        ///Margaret
        ///Ferdinand
        ///Perdita
        ///Mab
        ///Mimas
        ///Enceladus
        ///Tethys
        ///Dione
        ///Rhea
        ///Titan
        ///Hyperion
        ///Iapetus
        ///Phoebe
        ///Janus
        ///Epimetheus
        ///Helene
        ///Telesto
        ///Calypso
        ///Atlas
        ///Prometheus
        ///Pandora
        ///Pan
        ///Methone
        ///Pallene
        ///Polyde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string systemNames {
            get {
                return ResourceManager.GetString("systemNames", resourceCulture);
            }
        }
    }
}
